import fs from 'fs'

import rootPath from "./rootPath.js"
import { entites } from "./entites.js"
import { readDataFile } from "./wikipediaScraper.js"

const PATH = `${rootPath}/data/autogenerated/eleventy/entites.json`

async function writeEleventyData() {
  const wikipediaData = readDataFile()

  const reformattedEntites = entites.map(entite => {
    const wikipedia = wikipediaData[entite.id]
    return { ...entite, wikipedia }
  })

  await fs.writeFileSync(PATH, JSON.stringify(reformattedEntites, null, 2))
}

export { writeEleventyData }
