import fs from 'fs'
import fetch from 'node-fetch'
import yaml from 'js-yaml'

import rootPath from "../lib/rootPath.js"

const PATH = `${rootPath}/data/autogenerated/eleventy/entites.json`

function readEntites() {
  return JSON.parse(fs.readFileSync(PATH))
}

async function writeMdFile(entiteData) {
  const path = `${rootPath}/www/journaux/${entiteData.slug}.md`
  console.log(`writing to ${path}`)
  await fs.writeFileSync(
    path,
    `---\n${yaml.dump(entiteData)}---\n\n`
  )
}

async function generateWikipediaDataFile() {
  for (const entite of readEntites()) {
    if (!entite.journal) continue
    await writeMdFile(entite)
  }
}

async function generateActionnairesFile() {
  const path = `${rootPath}/data/autogenerated/eleventy/actionnaires.json`
  console.log(`writing to ${path}`)
  const entites = readEntites()
  await fs.writeFileSync(
    path,
    JSON.stringify(entites.filter(e => !e.journal), null, 2)
  )
}

// await generateWikipediaDataFile()
await generateActionnairesFile()

